import { Session } from '@supabase/supabase-js';
import * as Linking from 'expo-linking';
import { createContext, PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { Platform } from 'react-native';
import { supabase, supabaseConfigured } from './supabase';

type AuthValue={session:Session|null;loading:boolean;recoveryMode:boolean;message:string|null;signIn(email:string,password:string):Promise<void>;signUp(email:string,password:string):Promise<void>;signOut():Promise<void>;requestPasswordReset(email:string):Promise<void>;updatePassword(password:string):Promise<void>;clearMessage():void};
const Context=createContext<AuthValue|null>(null);
function redirectUrl(){return Platform.OS==='web' ? `${window.location.origin}${process.env.NODE_ENV==='production'?'/karate-tracker2':''}/account` : Linking.createURL('/account');}
async function applyNativeAuthUrl(url:string|null){if(!url||Platform.OS==='web')return false;const fragment=url.split('#')[1]??url.split('?')[1];if(!fragment)return false;const params=new URLSearchParams(fragment);const access_token=params.get('access_token'),refresh_token=params.get('refresh_token');if(access_token&&refresh_token)await supabase.auth.setSession({access_token,refresh_token});return params.get('type')==='recovery';}
export function AuthProvider({children}:PropsWithChildren){const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[recoveryMode,setRecoveryMode]=useState(false),[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);});const{data:{subscription}}=supabase.auth.onAuthStateChange((event,next)=>{setSession(next);if(event==='PASSWORD_RECOVERY')setRecoveryMode(true);});if(Platform.OS!=='web'){void Linking.getInitialURL().then(async url=>{if(await applyNativeAuthUrl(url))setRecoveryMode(true);});const link=Linking.addEventListener('url',({url})=>void applyNativeAuthUrl(url).then(recovery=>{if(recovery)setRecoveryMode(true);}));return()=>{subscription.unsubscribe();link.remove();};}return()=>subscription.unsubscribe();},[]);
 const run=useCallback(async(action:()=>Promise<{error:{message:string}|null}>,success?:string)=>{setMessage(null);const{error}=await action();if(error)throw new Error(error.message);if(success)setMessage(success);},[]);
 const value=useMemo<AuthValue>(()=>({session,loading,recoveryMode,message,signIn:(email,password)=>run(()=>supabase.auth.signInWithPassword({email:email.trim(),password})),signUp:(email,password)=>run(()=>supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:redirectUrl()}}),'Check your email to confirm your account.'),signOut:()=>run(()=>supabase.auth.signOut()),requestPasswordReset:(email)=>run(()=>supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:redirectUrl()}),'Password reset instructions have been sent.'),updatePassword:async(password)=>{await run(()=>supabase.auth.updateUser({password}),'Your password has been updated.');setRecoveryMode(false);},clearMessage:()=>setMessage(null)}),[session,loading,recoveryMode,message,run]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useAuth(){const value=useContext(Context);if(!value)throw new Error('useAuth must be used inside AuthProvider.');return value;}
export { supabaseConfigured };
