import { calendarRepository } from '@/data/calendar-storage';
import { OccurrenceException, OneOffEvent, WeeklySchedule } from '@/data/calendar-types';
import { sessionRepository } from '@/data/session-storage';
import { MartialArt, TrainingSession } from '@/data/session-types';
import { clearTombstones, listTombstones, SyncEntity, SyncTombstone } from './sync-metadata';
import { isNewerSyncTimestamp } from './sync-resolution';
import { supabase } from './supabase';

type CloudBase={id:string;user_id:string;updated_at:string;deleted_at:string|null};
type SessionRow=CloudBase&{training_date:string;start_time:string|null;end_time:string|null;martial_art:MartialArt;duration_minutes:number;notes:string|null;scheduled_occurrence_id:string|null;created_at:string};
type FocusRow={user_id:string;session_id:string;focus:string;role:'primary'|'additional';position:number;updated_at:string;deleted_at:string|null};
type ScheduleRow=CloudBase&{day_of_week:number;martial_art:MartialArt;start_time:string;end_time:string|null;expected_duration_minutes:number;location:string|null;notes:string|null;starts_on:string;created_at:string};
type OccurrenceRow=CloudBase&{schedule_id:string;occurrence_date:string;status:'skipped'|'completed';completed_session_id:string|null};
type EventRow=CloudBase&{event_type:OneOffEvent['type'];title:string;event_date:string;start_time:string|null;end_time:string|null;martial_art:MartialArt|null;location:string|null;notes:string|null;created_at:string};
export type SyncResult={downloaded:number;uploaded:number;deleted:number;completedAt:string};
const newer=isNewerSyncTimestamp;
function assertResult(error:{message:string}|null){if(error)throw new Error(error.message);}
async function fetchRows<T>(table:string){const result=await supabase.from(table).select('*');assertResult(result.error);return (result.data??[]) as unknown as T[];}
const remoteStamp=(row:CloudBase|undefined)=>row?.deleted_at??row?.updated_at;

export async function syncCloudData(userId:string):Promise<SyncResult>{
 const [remoteSessions,focuses,remoteSchedules,remoteOccurrences,remoteEvents,tombstones]=await Promise.all([fetchRows<SessionRow>('training_sessions'),fetchRows<FocusRow>('training_session_focuses'),fetchRows<ScheduleRow>('weekly_schedules'),fetchRows<OccurrenceRow>('schedule_occurrences'),fetchRows<EventRow>('calendar_events'),listTombstones()]);
 let downloaded=0,uploaded=0,deleted=0;const cleared:SyncTombstone[]=[];const tombMap=new Map(tombstones.map(item=>[`${item.entityType}:${item.recordId}`,item]));
 const localSessions=await sessionRepository.list(),localSchedules=await calendarRepository.listSchedules(),localOccurrences=await calendarRepository.listExceptions(),localEvents=await calendarRepository.listEvents();
 const localSessionMap=new Map(localSessions.map(item=>[item.id,item])),localScheduleMap=new Map(localSchedules.map(item=>[item.id,item])),localOccurrenceMap=new Map(localOccurrences.map(item=>[item.occurrenceId,item])),localEventMap=new Map(localEvents.map(item=>[item.id,item]));
 const focusMap=new Map<string,FocusRow[]>();for(const focus of focuses.filter(item=>!item.deleted_at)){const items=focusMap.get(focus.session_id)??[];items.push(focus);focusMap.set(focus.session_id,items);}
 for(const row of remoteSessions){const local=localSessionMap.get(row.id),tomb=tombMap.get(`session:${row.id}`),stamp=remoteStamp(row);if(tomb&&newer(tomb.deletedAt,stamp))continue;if(tomb){cleared.push(tomb);tombMap.delete(`session:${row.id}`);}if(row.deleted_at){if(!local||!newer(local.updatedAt,row.deleted_at)){await sessionRepository.deleteFromSync(row.id);localSessionMap.delete(row.id);downloaded++;}continue;}if(!local||newer(row.updated_at,local.updatedAt)){const fs=(focusMap.get(row.id)??[]).sort((a,b)=>a.position-b.position),primary=fs.find(item=>item.role==='primary')?.focus;if(!primary)continue;const item:TrainingSession={id:row.id,date:row.training_date,startTime:row.start_time,endTime:row.end_time,martialArt:row.martial_art,primaryFocus:primary,additionalFocuses:fs.filter(item=>item.role==='additional').map(item=>item.focus),durationMinutes:row.duration_minutes,notes:row.notes,scheduledOccurrenceId:row.scheduled_occurrence_id,createdAt:row.created_at,updatedAt:row.updated_at};await sessionRepository.upsertFromSync(item);localSessionMap.set(item.id,item);downloaded++;}}
 for(const row of remoteSchedules){const local=localScheduleMap.get(row.id),tomb=tombMap.get(`schedule:${row.id}`),stamp=remoteStamp(row);if(tomb&&newer(tomb.deletedAt,stamp))continue;if(tomb){cleared.push(tomb);tombMap.delete(`schedule:${row.id}`);}if(row.deleted_at){if(!local||!newer(local.updatedAt,row.deleted_at)){await calendarRepository.deleteScheduleFromSync(row.id);localScheduleMap.delete(row.id);downloaded++;}continue;}if(!local||newer(row.updated_at,local.updatedAt)){const item:WeeklySchedule={id:row.id,dayOfWeek:row.day_of_week,martialArt:row.martial_art,startTime:row.start_time,endTime:row.end_time,expectedDurationMinutes:row.expected_duration_minutes,location:row.location,notes:row.notes,startsOn:row.starts_on,createdAt:row.created_at,updatedAt:row.updated_at};await calendarRepository.upsertScheduleFromSync(item);localScheduleMap.set(item.id,item);downloaded++;}}
 for(const row of remoteEvents){const local=localEventMap.get(row.id),tomb=tombMap.get(`event:${row.id}`),stamp=remoteStamp(row);if(tomb&&newer(tomb.deletedAt,stamp))continue;if(tomb){cleared.push(tomb);tombMap.delete(`event:${row.id}`);}if(row.deleted_at){if(!local||!newer(local.updatedAt,row.deleted_at)){await calendarRepository.deleteEventFromSync(row.id);localEventMap.delete(row.id);downloaded++;}continue;}if(!local||newer(row.updated_at,local.updatedAt)){const item:OneOffEvent={id:row.id,type:row.event_type,title:row.title,date:row.event_date,startTime:row.start_time,endTime:row.end_time,martialArt:row.martial_art,location:row.location,notes:row.notes,createdAt:row.created_at,updatedAt:row.updated_at};await calendarRepository.upsertEventFromSync(item);localEventMap.set(item.id,item);downloaded++;}}
 for(const row of remoteOccurrences){const local=localOccurrenceMap.get(row.id),tomb=tombMap.get(`occurrence:${row.id}`),stamp=remoteStamp(row);if(tomb&&newer(tomb.deletedAt,stamp))continue;if(tomb){cleared.push(tomb);tombMap.delete(`occurrence:${row.id}`);}if(row.deleted_at){if(!local||!newer(local.updatedAt,row.deleted_at)){await calendarRepository.deleteExceptionFromSync(row.id);localOccurrenceMap.delete(row.id);downloaded++;}continue;}if(localScheduleMap.has(row.schedule_id)&&(!local||newer(row.updated_at,local.updatedAt))){const item:OccurrenceException={occurrenceId:row.id,scheduleId:row.schedule_id,date:row.occurrence_date,status:row.status,completedSessionId:row.completed_session_id,updatedAt:row.updated_at};await calendarRepository.upsertExceptionFromSync(item);localOccurrenceMap.set(item.occurrenceId,item);downloaded++;}}
 const remoteSessionMap=new Map(remoteSessions.map(item=>[item.id,item]));for(const item of localSessionMap.values()){const remote=remoteSessionMap.get(item.id),tomb=tombMap.get(`session:${item.id}`);if(tomb||newer(remoteStamp(remote),item.updatedAt))continue;const result=await supabase.from('training_sessions').upsert({id:item.id,user_id:userId,training_date:item.date,start_time:item.startTime,end_time:item.endTime,martial_art:item.martialArt,duration_minutes:item.durationMinutes,notes:item.notes,scheduled_occurrence_id:item.scheduledOccurrenceId,created_at:item.createdAt,updated_at:item.updatedAt,deleted_at:null},{onConflict:'user_id,id'});assertResult(result.error);const remove=await supabase.from('training_session_focuses').delete().eq('user_id',userId).eq('session_id',item.id);assertResult(remove.error);const rows=[{user_id:userId,session_id:item.id,focus:item.primaryFocus,role:'primary',position:0,updated_at:item.updatedAt,deleted_at:null},...item.additionalFocuses.map((focus,index)=>({user_id:userId,session_id:item.id,focus,role:'additional',position:index+1,updated_at:item.updatedAt,deleted_at:null}))];const focusResult=await supabase.from('training_session_focuses').insert(rows);assertResult(focusResult.error);uploaded++;}
 const remoteScheduleMap=new Map(remoteSchedules.map(item=>[item.id,item]));for(const item of localScheduleMap.values()){const remote=remoteScheduleMap.get(item.id);if(tombMap.has(`schedule:${item.id}`)||newer(remoteStamp(remote),item.updatedAt))continue;const result=await supabase.from('weekly_schedules').upsert({id:item.id,user_id:userId,day_of_week:item.dayOfWeek,martial_art:item.martialArt,start_time:item.startTime,end_time:item.endTime,expected_duration_minutes:item.expectedDurationMinutes,location:item.location,notes:item.notes,starts_on:item.startsOn,created_at:item.createdAt,updated_at:item.updatedAt,deleted_at:null},{onConflict:'user_id,id'});assertResult(result.error);uploaded++;}
 const remoteEventMap=new Map(remoteEvents.map(item=>[item.id,item]));for(const item of localEventMap.values()){const remote=remoteEventMap.get(item.id);if(tombMap.has(`event:${item.id}`)||newer(remoteStamp(remote),item.updatedAt))continue;const result=await supabase.from('calendar_events').upsert({id:item.id,user_id:userId,event_type:item.type,title:item.title,event_date:item.date,start_time:item.startTime,end_time:item.endTime,martial_art:item.martialArt,location:item.location,notes:item.notes,created_at:item.createdAt,updated_at:item.updatedAt,deleted_at:null},{onConflict:'user_id,id'});assertResult(result.error);uploaded++;}
 const remoteOccurrenceMap=new Map(remoteOccurrences.map(item=>[item.id,item]));for(const item of localOccurrenceMap.values()){const remote=remoteOccurrenceMap.get(item.occurrenceId);if(tombMap.has(`occurrence:${item.occurrenceId}`)||newer(remoteStamp(remote),item.updatedAt))continue;const result=await supabase.from('schedule_occurrences').upsert({id:item.occurrenceId,user_id:userId,schedule_id:item.scheduleId,occurrence_date:item.date,status:item.status,completed_session_id:item.completedSessionId,updated_at:item.updatedAt,deleted_at:null},{onConflict:'user_id,id'});assertResult(result.error);uploaded++;}
 const tables:Record<SyncEntity,string>={session:'training_sessions',schedule:'weekly_schedules',occurrence:'schedule_occurrences',event:'calendar_events'};for(const tomb of tombMap.values()){const result=await supabase.from(tables[tomb.entityType]).update({deleted_at:tomb.deletedAt,updated_at:tomb.deletedAt}).eq('user_id',userId).eq('id',tomb.recordId);assertResult(result.error);cleared.push(tomb);deleted++;}
 const preference=await supabase.from('app_preferences').upsert({user_id:userId,preferences:{sync_version:1},updated_at:new Date().toISOString(),deleted_at:null},{onConflict:'user_id'});assertResult(preference.error);await clearTombstones(cleared);return{downloaded,uploaded,deleted,completedAt:new Date().toISOString()};
}
