import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Href, useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { AppText } from '@/components/ui/app-text';
import { Card } from '@/components/ui/card';
import { ChoiceChip, PrimaryButton, SectionHeader } from '@/components/ui/controls';
import { Screen } from '@/components/ui/screen';
import { radius, spacing } from '@/constants/theme';
import { useCalendar } from '@/data/calendar-context';
import { addDays, CalendarEventType, formatTime, getOccurrences, localDateKey, OneOffEvent, OneOffEventDraft, ScheduleOccurrence, validateEvent, validateSchedule, weekdays, WeeklySchedule, WeeklyScheduleDraft } from '@/data/calendar-types';
import { useSessions } from '@/data/sessions-context';
import { formatDuration, formatSessionDate, focusOptions, MartialArt, TrainingSession } from '@/data/session-types';
import { useAppTheme } from '@/hooks/use-app-theme';

type Editor={kind:'schedule';item?:WeeklySchedule}|{kind:'event';item?:OneOffEvent}|null;
type CalendarItem={id:string;date:string;time:string;title:string;detail:string;kind:'scheduled'|'completed'|'skipped'|'event';occurrence?:ScheduleOccurrence;event?:OneOffEvent;session?:TrainingSession};
const eventTypes:CalendarEventType[]=['Planned training','Grading','Seminar','Other'];
async function confirm(message:string){if(Platform.OS==='web')return window.confirm(message);return new Promise<boolean>(resolve=>Alert.alert('Please confirm',message,[{text:'Cancel',style:'cancel',onPress:()=>resolve(false)},{text:'Delete',style:'destructive',onPress:()=>resolve(true)}],{cancelable:true,onDismiss:()=>resolve(false)}));}

export default function CalendarScreen(){
 const {colors}=useAppTheme();const calendar=useCalendar(),{sessions}=useSessions();
 const[view,setView]=useState<'Month'|'Agenda'>('Month'),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[editor,setEditor]=useState<Editor>(null);
 const refreshCalendar=calendar.refresh;useFocusEffect(useCallback(()=>{void refreshCalendar();},[refreshCalendar]));
 const monthStart=localDateKey(new Date(month.getFullYear(),month.getMonth(),1)),monthEnd=localDateKey(new Date(month.getFullYear(),month.getMonth()+1,0));
 const rangeStart=view==='Month'?monthStart:localDateKey(addDays(new Date(),-30)),rangeEnd=view==='Month'?monthEnd:localDateKey(addDays(new Date(),120));
 const occurrences=useMemo(()=>getOccurrences(calendar.schedules,calendar.exceptions,rangeStart,rangeEnd),[calendar.schedules,calendar.exceptions,rangeStart,rangeEnd]);
 const items=useMemo<CalendarItem[]>(()=>{const represented=new Set<string>();return [
  ...occurrences.map(o=>{const completed=sessions.find(session=>session.id===o.completedSessionId);if(completed)represented.add(completed.id);return{id:o.occurrenceId,date:o.date,time:completed?.startTime??o.schedule.startTime,title:completed?`${completed.martialArt} completed`:o.schedule.martialArt,detail:completed?`${completed.primaryFocus} · ${formatDuration(completed.durationMinutes)}`:`${formatTime(o.schedule.startTime)} · ${formatDuration(o.schedule.expectedDurationMinutes)}${o.schedule.location?` · ${o.schedule.location}`:''}`,kind:o.status==='completed'?'completed':o.status==='skipped'?'skipped':'scheduled',occurrence:o,session:completed} as CalendarItem;}),
  ...calendar.events.filter(e=>e.date>=rangeStart&&e.date<=rangeEnd).map(e=>({id:e.id,date:e.date,time:e.startTime??'',title:e.title,detail:`${e.type}${e.startTime?` · ${formatTime(e.startTime)}`:''}${e.location?` · ${e.location}`:''}`,kind:'event',event:e} as CalendarItem)),
  ...sessions.filter(s=>!represented.has(s.id)&&s.date>=rangeStart&&s.date<=rangeEnd).map(s=>({id:s.id,date:s.date,time:s.startTime??'',title:`${s.martialArt} completed`,detail:`${s.primaryFocus} · ${formatDuration(s.durationMinutes)}`,kind:'completed',session:s} as CalendarItem)),
 ].sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));},[occurrences,calendar.events,sessions,rangeStart,rangeEnd]);
 const marked=new Set(items.map(i=>i.date));
 const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const lead=(first.getDay()+6)%7;return Array.from({length:42},(_,i)=>{const d=new Date(month.getFullYear(),month.getMonth(),i-lead+1);return{date:d,key:localDateKey(d),inside:d.getMonth()===month.getMonth()};});},[month]);
 const empty=calendar.schedules.length===0&&calendar.events.length===0&&sessions.length===0;
 return <Screen title="Calendar" subtitle="Plans, training and important dates">
  <View style={s.addRow}><PrimaryButton onPress={()=>setEditor({kind:'schedule'})}>Add weekly schedule</PrimaryButton><Pressable style={[s.secondary,{borderColor:colors.border,backgroundColor:colors.surface}]} onPress={()=>setEditor({kind:'event'})}><MaterialCommunityIcons name="calendar-plus" size={19} color={colors.primary}/><AppText weight="bold">Add event</AppText></Pressable></View>
  {editor?.kind==='schedule'?<ScheduleEditor item={editor.item} onClose={()=>setEditor(null)}/>:null}
  {editor?.kind==='event'?<EventEditor item={editor.item} onClose={()=>setEditor(null)}/>:null}
  <View style={s.switcher}><ChoiceChip label="Month" selected={view==='Month'} onPress={()=>setView('Month')}/><ChoiceChip label="Agenda" selected={view==='Agenda'} onPress={()=>setView('Agenda')}/></View>
  {view==='Month'?<Card><View style={s.monthHead}><Pressable onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><MaterialCommunityIcons name="chevron-left" size={26} color={colors.textMuted}/></Pressable><AppText variant="heading" weight="bold">{month.toLocaleDateString('en-AU',{month:'long',year:'numeric'})}</AppText><Pressable onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><MaterialCommunityIcons name="chevron-right" size={26} color={colors.textMuted}/></Pressable></View><View style={s.week}>{['M','T','W','T','F','S','S'].map((d,i)=><AppText key={`${d}${i}`} variant="caption" weight="bold" color={colors.textMuted} style={s.day}>{d}</AppText>)}</View><View style={s.grid}>{cells.map(c=><View key={c.key} style={s.cell}><AppText variant="caption" color={c.inside?colors.text:colors.textMuted}>{c.date.getDate()}</AppText>{marked.has(c.key)?<View style={[s.dot,{backgroundColor:colors.primary}]}/>:null}</View>)}</View></Card>:null}
  {empty?<Card style={s.empty}><MaterialCommunityIcons name="calendar-blank-outline" size={32} color={colors.primary}/><AppText variant="heading" weight="bold">Your calendar is ready</AppText><AppText color={colors.textMuted} style={s.center}>Add a weekly training schedule, grading, seminar or one-off training event.</AppText></Card>:null}
  <SectionHeader title={view==='Month'?'This month':'Agenda'}/>{items.length===0&&!empty?<Card><AppText color={colors.textMuted}>Nothing is planned in this view.</AppText></Card>:items.map(item=><CalendarRow key={`${item.kind}-${item.id}`} item={item} onEdit={()=>item.event?setEditor({kind:'event',item:item.event}):item.occurrence?setEditor({kind:'schedule',item:item.occurrence.schedule}):undefined}/>) }
 </Screen>;
}

function CalendarRow({item,onEdit}:{item:CalendarItem;onEdit:()=>void}){const{colors}=useAppTheme(),router=useRouter(),calendar=useCalendar();const tint=item.kind==='completed'?colors.success:item.kind==='skipped'?colors.textMuted:item.kind==='event'?colors.accent:colors.primary;
 const log=()=>{const o=item.occurrence;if(!o)return;router.push({pathname:'/log',params:{scheduleId:o.schedule.id,occurrenceId:o.occurrenceId,date:o.date,art:o.schedule.martialArt,start:o.schedule.startTime,end:o.schedule.endTime??'',duration:String(o.schedule.expectedDurationMinutes)}} as Href);};
 return <Card style={s.item}><View style={[s.itemIcon,{backgroundColor:colors.surfaceMuted}]}><MaterialCommunityIcons name={item.kind==='completed'?'check':item.kind==='skipped'?'calendar-remove':item.kind==='event'?'star-outline':'calendar-clock'} size={21} color={tint}/></View><View style={s.copy}><AppText variant="caption" color={colors.textMuted}>{formatSessionDate(item.date,{weekday:'short',day:'numeric',month:'short'}).toUpperCase()}</AppText><AppText weight="bold">{item.title}</AppText><AppText variant="caption" color={colors.textMuted}>{item.detail}</AppText><AppText variant="caption" weight="bold" color={tint}>{item.kind.toUpperCase()}</AppText><View style={s.actions}>{item.kind==='scheduled'?<><Small label="Log as completed" onPress={log}/><Small label="Skip" onPress={()=>item.occurrence&&void calendar.skipOccurrence(item.occurrence.schedule.id,item.date)}/></>:null}{item.kind==='skipped'?<Small label="Restore" onPress={()=>item.occurrence&&void calendar.restoreOccurrence(item.occurrence.schedule.id,item.date)}/>:null}{item.event||item.occurrence?<Small label="Edit" onPress={onEdit}/>:null}</View></View></Card>;
}
function Small({label,onPress}:{label:string;onPress:()=>void}){const{colors}=useAppTheme();return <Pressable onPress={onPress} style={[s.small,{borderColor:colors.border}]}><AppText variant="caption" weight="bold" color={colors.primary}>{label}</AppText></Pressable>}

function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){const{colors}=useAppTheme();return <View style={[s.field,{backgroundColor:colors.surface,borderColor:colors.border}]}><AppText variant="caption" color={colors.textMuted}>{label.toUpperCase()}</AppText><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={colors.textMuted} style={[s.input,{color:colors.text}]}/></View>}
function ScheduleEditor({item,onClose}:{item?:WeeklySchedule;onClose:()=>void}){const calendar=useCalendar();const[day,setDay]=useState(item?.dayOfWeek??1),[art,setArt]=useState<MartialArt>(item?.martialArt??'Karate'),[start,setStart]=useState(item?.startTime??'18:00'),[end,setEnd]=useState(item?.endTime??''),[duration,setDuration]=useState(String(item?.expectedDurationMinutes??60)),[location,setLocation]=useState(item?.location??''),[notes,setNotes]=useState(item?.notes??''),[error,setError]=useState('');
 const save=async()=>{const draft:WeeklyScheduleDraft={dayOfWeek:day,martialArt:art,startTime:start,endTime:end,expectedDurationMinutes:Number(duration),location,notes};const message=validateSchedule(draft);if(message){setError(message);return;}if(item)await calendar.updateSchedule(item.id,draft);else await calendar.createSchedule(draft);onClose();};
 const remove=async()=>{if(item&&await confirm('Delete this recurring weekly schedule? Completed Diary training will remain.')){await calendar.deleteSchedule(item.id);onClose();}};
 return <Card style={s.editor}><AppText variant="heading" weight="bold">{item?'Edit weekly schedule':'New weekly schedule'}</AppText><View style={s.chips}>{weekdays.map((d,i)=><ChoiceChip key={d} label={d.slice(0,3)} selected={day===i} onPress={()=>setDay(i)}/>)}</View><View style={s.chips}>{(Object.keys(focusOptions) as MartialArt[]).map(a=><ChoiceChip key={a} label={a} selected={art===a} onPress={()=>setArt(a)}/>)}</View><View style={s.pair}><Field label="Start time" value={start} onChange={setStart} placeholder="18:00"/><Field label="End time (optional)" value={end} onChange={setEnd} placeholder="19:00"/></View><Field label="Expected whole minutes" value={duration} onChange={setDuration}/><Field label="Location (optional)" value={location} onChange={setLocation}/><Field label="Notes (optional)" value={notes} onChange={setNotes}/>{error?<AppText color="#A33A2B">{error}</AppText>:null}<View style={s.formActions}><PrimaryButton icon="check" onPress={()=>void save()}>Save schedule</PrimaryButton><Small label="Cancel" onPress={onClose}/>{item?<Small label="Delete schedule" onPress={()=>void remove()}/>:null}</View></Card>;
}
function EventEditor({item,onClose}:{item?:OneOffEvent;onClose:()=>void}){const calendar=useCalendar();const[type,setType]=useState<CalendarEventType>(item?.type??'Planned training'),[title,setTitle]=useState(item?.title??''),[date,setDate]=useState(item?.date??localDateKey(new Date())),[start,setStart]=useState(item?.startTime??''),[end,setEnd]=useState(item?.endTime??''),[art,setArt]=useState<MartialArt|null>(item?.martialArt??null),[location,setLocation]=useState(item?.location??''),[notes,setNotes]=useState(item?.notes??''),[error,setError]=useState('');
 const save=async()=>{const draft:OneOffEventDraft={type,title,date,startTime:start,endTime:end,martialArt:art,location,notes};const message=validateEvent(draft);if(message){setError(message);return;}if(item)await calendar.updateEvent(item.id,draft);else await calendar.createEvent(draft);onClose();};const remove=async()=>{if(item&&await confirm('Delete this calendar event?')){await calendar.deleteEvent(item.id);onClose();}};
 return <Card style={s.editor}><AppText variant="heading" weight="bold">{item?'Edit event':'New calendar event'}</AppText><View style={s.chips}>{eventTypes.map(t=><ChoiceChip key={t} label={t} selected={type===t} onPress={()=>setType(t)}/>)}</View><Field label="Title" value={title} onChange={setTitle}/><Field label="Date" value={date} onChange={setDate} placeholder="YYYY-MM-DD"/><View style={s.pair}><Field label="Start time (optional)" value={start} onChange={setStart} placeholder="09:00"/><Field label="End time (optional)" value={end} onChange={setEnd}/></View><AppText variant="caption" color="#6A716E">MARTIAL ART (OPTIONAL)</AppText><View style={s.chips}><ChoiceChip label="None" selected={!art} onPress={()=>setArt(null)}/>{(Object.keys(focusOptions) as MartialArt[]).map(a=><ChoiceChip key={a} label={a} selected={art===a} onPress={()=>setArt(a)}/>)}</View><Field label="Location (optional)" value={location} onChange={setLocation}/><Field label="Notes (optional)" value={notes} onChange={setNotes}/>{error?<AppText color="#A33A2B">{error}</AppText>:null}<View style={s.formActions}><PrimaryButton icon="check" onPress={()=>void save()}>Save event</PrimaryButton><Small label="Cancel" onPress={onClose}/>{item?<Small label="Delete event" onPress={()=>void remove()}/>:null}</View></Card>;
}
const s=StyleSheet.create({addRow:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},secondary:{minHeight:54,borderWidth:1,borderRadius:radius.md,paddingHorizontal:spacing.lg,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm},switcher:{flexDirection:'row',gap:spacing.sm,marginVertical:spacing.xl},monthHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:spacing.lg},week:{flexDirection:'row'},day:{width:'14.285%',textAlign:'center'},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:spacing.sm},cell:{width:'14.285%',height:42,alignItems:'center',gap:3},dot:{width:5,height:5,borderRadius:3},empty:{alignItems:'center',gap:spacing.md},center:{textAlign:'center'},item:{flexDirection:'row',gap:spacing.md,marginBottom:spacing.md},itemIcon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},copy:{flex:1,minWidth:0,gap:3},actions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.sm},small:{minHeight:34,borderWidth:1,borderRadius:radius.pill,paddingHorizontal:spacing.md,alignItems:'center',justifyContent:'center'},editor:{marginTop:spacing.lg,gap:spacing.md},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},field:{flex:1,minWidth:0,borderWidth:1,borderRadius:radius.md,paddingHorizontal:spacing.md,paddingVertical:spacing.sm,gap:2},input:{fontSize:16,minHeight:28},pair:{flexDirection:'row',flexWrap:'wrap',gap:spacing.md},formActions:{gap:spacing.sm}});
