import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, StyleSheet, useWindowDimensions, View } from 'react-native';
import { AppText } from '@/components/ui/app-text';
import { Card } from '@/components/ui/card';
import { ChoiceChip, PrimaryButton, SectionHeader } from '@/components/ui/controls';
import { ProgressRow } from '@/components/ui/metric';
import { Screen } from '@/components/ui/screen';
import { radius, spacing } from '@/constants/theme';
import { useSessions } from '@/data/sessions-context';
import { calculateProgressStats, ProgressPeriod } from '@/data/session-progress';
import { focusOptions, formatDuration, MartialArt } from '@/data/session-types';
import { useAppTheme } from '@/hooks/use-app-theme';

const periods: { key: ProgressPeriod; label: string }[] = [{ key: 'thisMonth', label: 'This month' }, { key: 'lastMonth', label: 'Last month' }, { key: 'allTime', label: 'All time' }];
const artLabels: Record<MartialArt,string>={Karate:'Karate practice',BJJ:'BJJ practice',Kobudo:'Kobudo / weapons'};

export default function ProgressScreen(){
 const {colors}=useAppTheme(),router=useRouter(),{width}=useWindowDimensions();const{sessions,loading,error,refresh}=useSessions();const[period,setPeriod]=useState<ProgressPeriod>('thisMonth');
 useFocusEffect(useCallback(()=>{void refresh();},[refresh]));const stats=useMemo(()=>calculateProgressStats(sessions,period),[sessions,period]);const compact=width<360;const selectedHasData=stats.completedSessions>0;const recentHasData=stats.monthlyTotals.some(item=>item.minutes>0);const maxArt=Math.max(...Object.values(stats.byArt),1);const maxMonth=Math.max(...stats.monthlyTotals.map(item=>item.minutes),1);
 return <Screen title="Progress" subtitle="Clear patterns from your completed training">
  <View style={s.chips}>{periods.map(item=><ChoiceChip key={item.key} label={item.label} selected={period===item.key} onPress={()=>setPeriod(item.key)}/>)}</View>
  {loading?<ActivityIndicator style={s.state} color={colors.primary}/>:null}{error?<Card style={s.state}><AppText weight="bold" color={colors.primary}>Progress unavailable</AppText><AppText color={colors.textMuted}>{error}</AppText></Card>:null}
  {!loading&&!error&&sessions.length===0?<Card style={s.empty}><MaterialCommunityIcons name="chart-box-outline" size={34} color={colors.primary}/><AppText variant="heading" weight="bold">Your progress will build here</AppText><AppText color={colors.textMuted} style={s.center}>Log completed training to see time, consistency, disciplines and practice patterns.</AppText><PrimaryButton onPress={()=>router.navigate('/log')}>Log training</PrimaryButton></Card>:null}
  {sessions.length>0&&!selectedHasData?<Card style={s.periodEmpty}><AppText weight="bold">No completed training in this period</AppText><AppText color={colors.textMuted}>Choose another period or log a session to add to these statistics.</AppText></Card>:null}
  {selectedHasData?<>
   <SectionHeader title="Progress summary"/><View style={[s.metrics,compact&&s.stack]}><Summary label="Training time" value={formatDuration(stats.totalMinutes)}/><Summary label="Training days" value={String(stats.trainingDays)}/><Summary label="Sessions" value={String(stats.completedSessions)}/></View><View style={[s.metrics,compact&&s.stack]}><Summary label="Current streak" value={`${stats.currentWeeklyStreak} ${stats.currentWeeklyStreak===1?'week':'weeks'}`} detail="All-time weekly streak"/><Summary label="Best streak" value={`${stats.bestWeeklyStreak} ${stats.bestWeeklyStreak===1?'week':'weeks'}`} detail="Personal best"/></View>
   <SectionHeader title="Hours by discipline"/><Card><ProgressRow label="Karate" value={formatDuration(stats.byArt.Karate)} progress={stats.byArt.Karate/maxArt} color={colors.karate}/><ProgressRow label="BJJ" value={formatDuration(stats.byArt.BJJ)} progress={stats.byArt.BJJ/maxArt} color={colors.bjj}/><ProgressRow label="Kobudo" value={formatDuration(stats.byArt.Kobudo)} progress={stats.byArt.Kobudo/maxArt} color={colors.kobudo}/></Card>
  </>:null}
  {sessions.length>0?<><SectionHeader title="Monthly training trend"/>{recentHasData?<Card><View style={s.chart}>{stats.monthlyTotals.map((item,index)=><View key={item.key} style={s.column}><AppText variant="caption" weight="bold" color={item.minutes?colors.text:colors.textMuted} style={s.chartValue}>{shortDuration(item.minutes)}</AppText><View style={s.barArea}><View style={[s.bar,{height:item.minutes?Math.max(5,Math.round(item.minutes/maxMonth*108)):3,backgroundColor:index===stats.monthlyTotals.length-1?colors.primary:item.minutes?colors.primarySoft:colors.surfaceMuted}]}/></View><AppText variant="caption" color={colors.textMuted}>{item.label}</AppText></View>)}</View></Card>:<Card><AppText color={colors.textMuted}>No training has been logged in the most recent six months.</AppText></Card>}</>:null}
  {selectedHasData?(Object.keys(focusOptions) as MartialArt[]).map(art=>{const total=Object.values(stats.focusOccurrences[art]).reduce((sum,count)=>sum+count,0);if(!total)return null;return <View key={art}><SectionHeader title={artLabels[art]}/><Card>{focusOptions[art].map((focus,index)=><OccurrenceRow key={focus} label={focus} count={stats.focusOccurrences[art][focus]} last={index===focusOptions[art].length-1}/>)}{art==='BJJ'?<View style={[s.rolling,{borderTopColor:colors.border}]}><View style={s.rollingCopy}><AppText weight="bold">Primary Rolling Time</AppText><AppText variant="caption" color={colors.textMuted}>Full duration only when Rolling was the primary focus</AppText></View><AppText weight="bold" color={colors.bjj}>{formatDuration(stats.primaryRollingMinutes)}</AppText></View>:null}</Card></View>}):null}
 </Screen>;
}
function Summary({label,value,detail}:{label:string;value:string;detail?:string}){const{colors}=useAppTheme();return <Card style={s.summary}><AppText variant="label" weight="bold" color={colors.textMuted}>{label.toUpperCase()}</AppText><AppText variant="heading" weight="bold" style={s.summaryValue}>{value}</AppText>{detail?<AppText variant="caption" color={colors.textMuted}>{detail}</AppText>:null}</Card>}
function OccurrenceRow({label,count,last}:{label:string;count:number;last:boolean}){const{colors}=useAppTheme();return <View style={[s.occurrence,!last&&{borderBottomWidth:1,borderBottomColor:colors.border}]}><AppText>{label}</AppText><AppText weight="bold" color={count?colors.primary:colors.textMuted}>{count} {count===1?'practice':'practices'}</AppText></View>}
function shortDuration(minutes:number){if(!minutes)return '0';const hours=Math.floor(minutes/60),remainder=minutes%60;if(!hours)return `${remainder}m`;if(!remainder)return `${hours}h`;return `${hours}h ${remainder}m`}
const s=StyleSheet.create({chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},state:{marginTop:spacing.xl},empty:{marginTop:spacing.xl,alignItems:'center',gap:spacing.md},center:{textAlign:'center'},periodEmpty:{marginTop:spacing.xl,gap:spacing.sm},metrics:{flexDirection:'row',gap:spacing.md,marginBottom:spacing.md},stack:{flexDirection:'column'},summary:{flex:1,minWidth:0,minHeight:112},summaryValue:{marginTop:spacing.md},chart:{height:190,flexDirection:'row',alignItems:'flex-end',gap:spacing.xs},column:{flex:1,minWidth:0,height:'100%',alignItems:'center',justifyContent:'flex-end'},chartValue:{fontSize:10,lineHeight:14,textAlign:'center'},barArea:{height:116,width:'100%',alignItems:'center',justifyContent:'flex-end',marginVertical:spacing.xs},bar:{width:28,maxWidth:'72%',borderTopLeftRadius:radius.sm,borderTopRightRadius:radius.sm},occurrence:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},rolling:{marginTop:spacing.md,paddingTop:spacing.md,borderTopWidth:1,flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:spacing.md},rollingCopy:{flex:1,minWidth:180,gap:2}});
