import { useState } from 'react';
import { ActivityIndicator, StyleSheet, TextInput, View } from 'react-native';
import { AppText } from '@/components/ui/app-text';
import { Card } from '@/components/ui/card';
import { ChoiceChip, PrimaryButton, SectionHeader } from '@/components/ui/controls';
import { Screen } from '@/components/ui/screen';
import { radius, spacing } from '@/constants/theme';
import { useAuth } from '@/cloud/auth-context';
import { useSync } from '@/cloud/sync-context';
import { useAppTheme } from '@/hooks/use-app-theme';
type Mode='signIn'|'signUp'|'reset';
export default function AccountScreen(){const{colors}=useAppTheme();const auth=useAuth(),sync=useSync();const[mode,setMode]=useState<Mode>('signIn'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const submit=async()=>{setError(null);if(mode!=='reset'&&password.length<8){setError('Use a password with at least 8 characters.');return;}if((mode==='signUp'||auth.recoveryMode)&&password!==confirm){setError('The two passwords do not match.');return;}setBusy(true);try{if(auth.recoveryMode)await auth.updatePassword(password);else if(mode==='signIn')await auth.signIn(email,password);else if(mode==='signUp')await auth.signUp(email,password);else await auth.requestPasswordReset(email);}catch(reason){setError(reason instanceof Error?reason.message:'Please try again.');}finally{setBusy(false);}};
 if(auth.loading)return <Screen title="Account"><ActivityIndicator color={colors.primary}/></Screen>;
 if(auth.session&&!auth.recoveryMode)return <Screen title="Account" subtitle="Cloud sync and account settings"><Card style={s.card}><AppText variant="label" color={colors.textMuted}>SIGNED IN AS</AppText><AppText variant="heading" weight="bold">{auth.session.user.email}</AppText></Card><SectionHeader title="Sync status"/><Card style={s.card}><AppText weight="bold">{sync.status==='needsChoice'?'Existing local training found':sync.status==='syncing'?'Syncing…':sync.status==='synced'?'Up to date':sync.status==='localOnly'?'Local only':sync.status==='error'?'Sync needs attention':'Ready'}</AppText>{sync.status==='needsChoice'?<><AppText color={colors.textMuted}>Would you like to upload and sync the training already stored on this device?</AppText><PrimaryButton icon="cloud-upload-outline" onPress={()=>void sync.chooseExistingData(true)}>Sync existing local data</PrimaryButton><PrimaryButton icon="cellphone" onPress={()=>void sync.chooseExistingData(false)}>Not now</PrimaryButton></>:null}{sync.status==='localOnly'?<><AppText color={colors.textMuted}>Nothing has been uploaded. You can enable sync whenever you are ready.</AppText><PrimaryButton icon="cloud-upload-outline" onPress={()=>void sync.chooseExistingData(true)}>Enable cloud sync</PrimaryButton></>:null}{sync.status==='synced'&&sync.lastResult?<AppText color={colors.textMuted}>Last sync: {new Date(sync.lastResult.completedAt).toLocaleString('en-AU')}</AppText>:null}{sync.error?<AppText color={colors.primary}>{sync.error}</AppText>:null}{sync.status!=='needsChoice'&&sync.status!=='localOnly'?<PrimaryButton icon="sync" disabled={sync.status==='syncing'} onPress={()=>void sync.syncNow()}>Sync now</PrimaryButton>:null}</Card><View style={s.action}><PrimaryButton icon="logout" disabled={busy} onPress={()=>void auth.signOut()}>Sign out</PrimaryButton></View></Screen>;
 const recovery=auth.recoveryMode;return <Screen title={recovery?'Choose a new password':'Account'} subtitle={recovery?'Enter a new password for your account':'Sign in to sync training across devices'}>{!recovery?<View style={s.tabs}><ChoiceChip label="Sign in" selected={mode==='signIn'} onPress={()=>setMode('signIn')}/><ChoiceChip label="Create account" selected={mode==='signUp'} onPress={()=>setMode('signUp')}/><ChoiceChip label="Reset password" selected={mode==='reset'} onPress={()=>setMode('reset')}/></View>:null}<Card style={s.form}>{!recovery?<Field label="Email" value={email} onChange={setEmail} secure={false}/>:null}{mode!=='reset'||recovery?<Field label="Password" value={password} onChange={setPassword} secure/>:null}{mode==='signUp'||recovery?<Field label="Confirm password" value={confirm} onChange={setConfirm} secure/>:null}{error?<AppText color={colors.primary}>{error}</AppText>:null}{auth.message?<AppText color={colors.success}>{auth.message}</AppText>:null}<PrimaryButton icon={mode==='reset'?'email-outline':'account-check-outline'} disabled={busy} onPress={()=>void submit()}>{busy?'Please wait…':recovery?'Update password':mode==='signIn'?'Sign in':mode==='signUp'?'Create account':'Send reset email'}</PrimaryButton></Card><Card style={s.note}><AppText variant="caption" color={colors.textMuted}>Training remains stored locally while signed out. Existing local data will not be uploaded without your approval.</AppText></Card></Screen>}
function Field({label,value,onChange,secure}:{label:string;value:string;onChange:(v:string)=>void;secure:boolean}){const{colors}=useAppTheme();return <View style={s.field}><AppText variant="caption" color={colors.textMuted}>{label.toUpperCase()}</AppText><TextInput autoCapitalize="none" autoCorrect={false} secureTextEntry={secure} value={value} onChangeText={onChange} keyboardType={secure?'default':'email-address'} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/></View>}
const s=StyleSheet.create({tabs:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},form:{marginTop:spacing.xl,gap:spacing.lg},field:{gap:spacing.xs},input:{minHeight:50,borderWidth:1,borderRadius:radius.md,paddingHorizontal:spacing.md,fontSize:16},card:{gap:spacing.sm},action:{marginTop:spacing.xl},note:{marginTop:spacing.md}});
